-- READ ONLY. Migration 002 verification. Run each numbered SELECT independently.
-- 1. Exact signature, return type, language, volatility, owner and security configuration; exactly one same-name function is allowed.
select n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) arguments,pg_get_function_result(p.oid) result_type,l.lanname language,p.provolatile,p.proowner::regrole owner,p.prosecdef,p.proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname='openingfit_missions_schema_readiness' order by 3;
-- 2. Effective execute privileges for every API/backend role.
select r.role_name,has_function_privilege(r.role_oid,to_regprocedure('public.openingfit_missions_schema_readiness()'),'execute') execute from (values(0::oid,'PUBLIC'),('anon'::regrole::oid,'anon'),('authenticated'::regrole::oid,'authenticated'),('service_role'::regrole::oid,'service_role')) r(role_oid,role_name) order by 2;
-- 3. Exact secret-free aggregate readiness output. Expected: {"ready": true, "schemaVersion": 1}.
select public.openingfit_missions_schema_readiness() readiness;
-- 4. Exact fail-closed classification. Expected: stage_complete.
select case when (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='openingfit_missions_schema_readiness')=1 and exists(select 1 from pg_proc p join pg_language l on l.oid=p.prolang where p.oid=to_regprocedure('public.openingfit_missions_schema_readiness()') and p.prorettype='jsonb'::regtype and l.lanname='sql' and p.provolatile='s' and p.prosecdef and p.proconfig @> array['search_path=public']) and not has_function_privilege(0,to_regprocedure('public.openingfit_missions_schema_readiness()'),'execute') and not has_function_privilege('anon',to_regprocedure('public.openingfit_missions_schema_readiness()'),'execute') and not has_function_privilege('authenticated',to_regprocedure('public.openingfit_missions_schema_readiness()'),'execute') and has_function_privilege('service_role',to_regprocedure('public.openingfit_missions_schema_readiness()'),'execute') and public.openingfit_missions_schema_readiness() is not distinct from jsonb_build_object('ready',true,'schemaVersion',1) then 'stage_complete' else 'stage_partial' end classification;
