-- READ ONLY. Split stage 001B verification. Run each numbered SELECT independently.
-- 1. Stage relations, columns and constraints.
select name,to_regclass('public.'||name) object from unnest(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) name;
select table_name,column_name,data_type,udt_name,is_nullable,column_default from information_schema.columns where table_schema='public' and table_name=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1,ordinal_position;
select c.conrelid::regclass,c.conname,c.contype,pg_get_constraintdef(c.oid) from pg_constraint c where c.conrelid=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']::regclass[]) order by 1,2;
-- 2. Indexes, RLS, policies, grants and triggers relevant to this and prior stages.
select tablename,indexname,indexdef from pg_indexes where schemaname='public' and tablename=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1,2;
select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1;
select tablename,policyname,roles,cmd,qual,with_check from pg_policies where schemaname='public' and tablename=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1,2;
select table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and table_name=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1,2,3;
select event_object_table,trigger_name,action_timing,event_manipulation,action_statement from information_schema.triggers where event_object_schema='public' and event_object_table=any(array['openingfit_missions','openingfit_mission_training_attempts','openingfit_mission_encounters','openingfit_mission_status_events']) order by 1,2;
-- 3. Functions and execution privileges.
select p.proname,pg_get_function_identity_arguments(p.oid),p.prosecdef,p.proconfig,has_function_privilege('public',p.oid,'execute') public_execute,has_function_privilege('anon',p.oid,'execute') anon_execute,has_function_privilege('authenticated',p.oid,'execute') authenticated_execute,has_function_privilege('service_role',p.oid,'execute') service_execute from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=any(array['openingfit_protect_mission_identity']) order by 1,2;
-- 4. Stage classification aid. Expected: prior tables plus RLS, four owner-select policies, exact grants and identity trigger.
select case when not ((select count(*) from pg_policies where schemaname='public' and policyname like 'openingfit_mission%select_own')=4 and exists(select 1 from pg_trigger where tgrelid=to_regclass('public.openingfit_missions') and tgname='openingfit_protect_mission_identity' and not tgisinternal) and not exists(select 1 from (values('openingfit_missions'),('openingfit_mission_training_attempts'),('openingfit_mission_encounters'),('openingfit_mission_status_events')) t(name) cross join (values(0::oid,'public'),('anon'::regrole::oid,'anon'),('authenticated'::regrole::oid,'authenticated'),('service_role'::regrole::oid,'service_role')) r(oid,name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(name) where has_table_privilege(r.oid,to_regclass('public.'||t.name),p.name) is distinct from (case when r.name='authenticated' then p.name='SELECT' when r.name='service_role' then p.name in ('SELECT','INSERT') or (t.name='openingfit_missions' and p.name='UPDATE') else false end))) then case when to_regclass('public.openingfit_missions') is null then 'stage_absent' else 'stage_partial' end else 'stage_complete' end classification;
