import { buildEvidenceSufficiency } from "../lib/evidenceSufficiency.js";

const ROLE_LABELS = { white: "White", black_vs_e4: "Black vs 1.e4", black_vs_d4: "Black vs 1.d4/other" };

export default function EvidenceSufficiencySummary({ report, onReanalyse }) {
  const view = buildEvidenceSufficiency(report);
  if (view.systemicFailure) return <section className="evidenceReconciliationWarning" role="alert"><strong>Analysis could not attribute the imported games reliably</strong><p>{view.imported} games were imported, but role attribution failed systemically. OpeningFit has not manufactured a weakness from this sample.</p>{view.diagnosticReference ? <small>Diagnostic reference: {view.diagnosticReference}</small> : null}<button type="button" className="primaryBtn" onClick={onReanalyse}>Reanalyse</button></section>;
  return <section className="evidenceSufficiencySummary" aria-labelledby="evidence-sufficiency-title"><header><h3 id="evidence-sufficiency-title">Evidence by repertoire role</h3><p>Observed results and recommendation strength are shown separately.</p></header>{view.warning ? <p className="evidenceReconciliationWarning" role="status"><strong>{view.imported} games imported; {view.usable} used for opening evidence.</strong> Review the exclusion reasons below rather than treating this as an account with too few games.{view.diagnosticReference ? ` Diagnostic reference: ${view.diagnosticReference}.` : ""}</p> : null}<div>{view.roles.map((role) => <article key={role.identity}><strong>{ROLE_LABELS[role.identity] || role.identity}</strong><span>{role.label}</span><p>{role.games} relevant game{role.games === 1 ? "" : "s"} observed. Recommendation strength: {role.recommendationStrength.replaceAll("_", " ")}.</p>{role.state === "limited" ? <small>Confidence is limited by the relevant role sample. {role.additionalForDeveloping} additional relevant game{role.additionalForDeveloping === 1 ? "" : "s"} would reach developing evidence. Safest next step: review one repeated position without changing the whole repertoire.</small> : role.state === "developing" ? <small>The pattern is useful but provisional. {role.additionalForStrong} additional relevant game{role.additionalForStrong === 1 ? "" : "s"} would improve sample confidence.</small> : <small>This sample supports a firm recommendation; the underlying chess claim still depends on the observed pattern.</small>}</article>)}</div></section>;
}
