import { useState } from "react";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";

const PRIMARY_SITE_URL = "https://www.openingfit.com";

function getOpeningName(opening) {
  return opening?.name || opening?.opening || opening?.label || opening?.openingName || "Unknown opening";
}

function getGames(opening) {
  return Number(opening?.games ?? opening?.count ?? opening?.total ?? 0);
}

function getWinRate(opening) {
  return Number(opening?.win_rate ?? opening?.winRate ?? opening?.score ?? 0);
}

function getVerdict(opening) {
  return opening?.fitVerdict || opening?.verdict || opening?.recommendation || "";
}

function cleanText(value) {
  return String(value || "")
    .replace(/[^\x20-\x7E£€]/g, "")
    .trim();
}

function getTodayText() {
  return new Date().toLocaleDateString("en-GB", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function getReportUrl() {
  return PRIMARY_SITE_URL;
}

function getShareText(username) {
  const name = username ? ` for ${username}` : "";
  return `I just generated my Opening Fit chess opening report${name}. Try it here: ${getReportUrl()}`;
}

function addFooter(doc) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by Opening Fit", 16, 287);
  doc.text(getReportUrl(), 150, 287);
}

function checkPage(doc, y) {
  if (y < 260) return y;

  addFooter(doc);
  doc.addPage();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, 210, 297, "F");
  return 20;
}

function addSectionTitle(doc, title, y) {
  y = checkPage(doc, y);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text(cleanText(title), 16, y);

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.6);
  doc.line(16, y + 4, 194, y + 4);

  return y + 13;
}

function drawSoftCard(doc, x, y, width, height) {
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(x, y, width, height, 4, 4, "FD");
}

function addBadge(doc, text, x, y) {
  const value = cleanText(text || "Info");
  const lower = value.toLowerCase();

  if (lower.includes("avoid")) {
    doc.setFillColor(254, 242, 242);
    doc.setTextColor(185, 28, 28);
  } else if (lower.includes("improve")) {
    doc.setFillColor(255, 247, 237);
    doc.setTextColor(194, 65, 12);
  } else if (lower.includes("keep")) {
    doc.setFillColor(240, 253, 244);
    doc.setTextColor(21, 128, 61);
  } else {
    doc.setFillColor(239, 246, 255);
    doc.setTextColor(30, 64, 175);
  }

  const width = Math.max(24, doc.getTextWidth(value) + 8);
  doc.roundedRect(x, y, width, 8, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text(value, x + 4, y + 5.5);

  doc.setTextColor(15, 23, 42);
}

function addInfoCard(doc, label, value, x, y, width) {
  drawSoftCard(doc, x, y, width, 25);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(cleanText(label).toUpperCase(), x + 5, y + 8);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);

  const valueLines = doc.splitTextToSize(cleanText(value), width - 10);
  doc.text(valueLines.slice(0, 2), x + 5, y + 17);
}

function addSnapshotCard(doc, label, opening, x, y, width) {
  if (!opening) return;

  drawSoftCard(doc, x, y, width, 43);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(cleanText(label).toUpperCase(), x + 5, y + 8);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);

  const nameLines = doc.splitTextToSize(cleanText(getOpeningName(opening)), width - 10);
  doc.text(nameLines.slice(0, 2), x + 5, y + 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`${getGames(opening)} games`, x + 5, y + 31);
  doc.text(`${getWinRate(opening).toFixed(0)}% score`, x + 5, y + 38);

  if (getVerdict(opening)) {
    addBadge(doc, getVerdict(opening), x + width - 31, y + 32);
  }
}

function addOpeningList(doc, title, openings, y, maxItems = 5) {
  if (!openings?.length) return y;

  y = addSectionTitle(doc, title, y);

  openings.slice(0, maxItems).forEach((opening, index) => {
    y = checkPage(doc, y);

    drawSoftCard(doc, 16, y, 178, 23);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(15, 23, 42);

    const name = `${index + 1}. ${getOpeningName(opening)}`;
    const nameLines = doc.splitTextToSize(cleanText(name), 112);
    doc.text(nameLines.slice(0, 1), 21, y + 8);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(`${getGames(opening)} games`, 21, y + 17);
    doc.text(`${getWinRate(opening).toFixed(0)}% score`, 57, y + 17);

    if (getVerdict(opening)) {
      addBadge(doc, getVerdict(opening), 155, y + 7);
    }

    y += 28;
  });

  return y + 2;
}

async function createReportPdf({ username, platform, gamesImported, openings = [], fitData }) {
  const doc = new jsPDF();

  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, 210, 297, "F");

  const usableOpenings = openings
    .filter(Boolean)
    .filter((opening) => !getOpeningName(opening).toLowerCase().includes("unknown"));

  const mostPlayed = [...usableOpenings].sort((a, b) => getGames(b) - getGames(a))[0];

  const strongest = [...usableOpenings]
    .filter((opening) => !String(getVerdict(opening)).toLowerCase().includes("avoid"))
    .sort((a, b) => getWinRate(b) - getWinRate(a))[0];

  const needsReview = [...usableOpenings]
    .sort((a, b) => getWinRate(a) - getWinRate(b))[0];

  const keepOpenings = usableOpenings.filter((opening) =>
    String(getVerdict(opening)).toLowerCase().includes("keep")
  );

  const improveOpenings = usableOpenings.filter((opening) =>
    String(getVerdict(opening)).toLowerCase().includes("improve")
  );

  const avoidOpenings = usableOpenings.filter((opening) =>
    String(getVerdict(opening)).toLowerCase().includes("avoid")
  );

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 48, "F");

  doc.setFillColor(37, 99, 235);
  doc.roundedRect(16, 12, 28, 22, 4, 4, "F");

  doc.setFillColor(96, 165, 250);
  doc.circle(190, 10, 22, "F");

  doc.setFillColor(34, 197, 94);
  doc.circle(203, 34, 18, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("OF", 25, 26);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("Opening Fit Report", 52, 21);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  doc.text(`Generated ${getTodayText()}`, 52, 31);

  let y = 61;

  addInfoCard(doc, "Username", username || "Unknown", 16, y, 54);
  addInfoCard(doc, "Platform", platform || "Chess.com / Lichess", 78, y, 54);
  addInfoCard(doc, "Games imported", String(Number(gamesImported || 0)), 140, y, 54);

  y += 38;

  y = addSectionTitle(doc, "Quick snapshot", y);

  addSnapshotCard(doc, "Strongest opening", strongest, 16, y, 56);
  addSnapshotCard(doc, "Most played", mostPlayed, 77, y, 56);
  addSnapshotCard(doc, "Needs review", needsReview, 138, y, 56);

  y += 55;

  y = addOpeningList(doc, "Keep", keepOpenings, y, 5);
  y = addOpeningList(doc, "Improve", improveOpenings, y, 5);
  y = addOpeningList(doc, "Improve / review", avoidOpenings, y, 5);

  const styleText = fitData?.summary || fitData?.styleSummary || fitData?.profileSummary;

  if (styleText) {
    y = addSectionTitle(doc, "Style notes", y);
    y = checkPage(doc, y);

    drawSoftCard(doc, 16, y, 178, 35);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);

    const lines = doc.splitTextToSize(cleanText(styleText), 168);
    doc.text(lines.slice(0, 4), 21, y + 9);

    y += 44;
  }

  y = addSectionTitle(doc, "Next steps", y);

  const nextSteps = [
    "Review the lowest-scoring repeated sample first and check where the pattern starts.",
    "Keep playing openings marked Keep if they match your style and results.",
    "Use the practice lines to drill common move orders.",
    "Import again after more games to see if your opening report improves.",
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  nextSteps.forEach((step, index) => {
    y = checkPage(doc, y);
    doc.text(`${index + 1}. ${step}`, 20, y);
    y += 8;
  });

  y += 4;
  y = checkPage(doc, y);

  drawSoftCard(doc, 16, y, 178, 34);

  const qrCodeImage = await QRCode.toDataURL(getReportUrl(), {
    width: 140,
    margin: 1,
  });

  doc.addImage(qrCodeImage, "PNG", 21, y + 5, 24, 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("Create your own Opening Fit report", 53, y + 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("Scan the QR code or visit:", 53, y + 20);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text(getReportUrl(), 53, y + 28);

  addFooter(doc);

  return doc;
}

export default function OpeningReportActions({
  username,
  platform,
  gamesImported,
  openings = [],
  fitData,
}) {
  const [copyStatus, setCopyStatus] = useState("");
  const hasReportData = openings?.length > 0 || gamesImported > 0;

  if (!hasReportData) return null;

  const filename = `opening-fit-report-${username || "player"}.pdf`;

  async function downloadPdf() {
    const doc = await createReportPdf({
      username,
      platform,
      gamesImported,
      openings,
      fitData,
    });

    doc.save(filename);
  }

  async function shareReport() {
    const shareText = getShareText(username);

    try {
      if (navigator.share) {
        await navigator.share({
          title: "Opening Fit Report",
          text: shareText,
          url: getReportUrl(),
        });
        return;
      }

      await navigator.clipboard.writeText(shareText);
      setCopyStatus("Share text copied.");
    } catch {
      await downloadPdf();
    }
  }

  async function copyShareText() {
    try {
      await navigator.clipboard.writeText(getShareText(username));
      setCopyStatus("Copied.");
      setTimeout(() => setCopyStatus(""), 1800);
    } catch {
      setCopyStatus("Could not copy.");
    }
  }

  function openShareUrl(type) {
    const url = encodeURIComponent(getReportUrl());
    const text = encodeURIComponent(getShareText(username));
    const title = encodeURIComponent("My Opening Fit chess report");

    const links = {
      x: `https://twitter.com/intent/tweet?url=${url}&text=${text}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${text}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${url}`,
      whatsapp: `https://api.whatsapp.com/send?text=${text}`,
      email: `mailto:?subject=${title}&body=${text}`,
    };

    window.open(links[type], "_blank", "noopener,noreferrer");
  }

  return (
    <section className="card reportActionsCard">
      <div className="reportActionsHeader">
        <div>
          <p className="eyebrow">Export and share</p>
          <h2>Opening report PDF</h2>
          <p>Download or share your report.</p>
        </div>
      </div>

      <div className="reportActionButtons">
        <button type="button" className="downloadReportButton" onClick={downloadPdf}>
          Download PDF
        </button>

        <button type="button" className="shareReportButton" onClick={shareReport}>
          Share
        </button>
      </div>

      <div className="socialShareButtons">
        <button type="button" onClick={() => openShareUrl("x")}>X</button>
        <button type="button" onClick={() => openShareUrl("facebook")}>Facebook</button>
        <button type="button" onClick={() => openShareUrl("linkedin")}>LinkedIn</button>
        <button type="button" onClick={() => openShareUrl("whatsapp")}>WhatsApp</button>
        <button type="button" onClick={() => openShareUrl("email")}>Email</button>
        <button type="button" onClick={copyShareText}>Copy text</button>
      </div>

      {copyStatus ? <p className="reportCopyStatus">{copyStatus}</p> : null}

      <p className="reportShareNote">
        PDF downloads to your device. Social buttons share the link and report text.
      </p>
    </section>
  );
}
