import { useEffect, useState } from "react";
import { CHANGELOG } from "../content/changelog";
import { supportPath } from "../lib/trustExperience";
import { DEFAULT_PUBLIC_ANALYSIS_CONTRACT, loadPublicAnalysisContract } from "../lib/productTransparency.js";

export default function PublicTrustPage({ page, appTopNav }) {
  const [analysisContract, setAnalysisContract] = useState(DEFAULT_PUBLIC_ANALYSIS_CONTRACT);
  useEffect(() => {
    if (page !== "how") return undefined;
    let active = true;
    loadPublicAnalysisContract().then((value) => { if (active) setAnalysisContract(value); }).catch(() => {});
    return () => { active = false; };
  }, [page]);
  const sections = {
    about: <><h1>Opening guidance built for real club-player games.</h1><p>OpeningFit exists because opening advice often starts with theory lists rather than the positions a player actually reaches. It is an independently built product by Daniel, designed to turn public online games into manageable repertoire and training decisions.</p><h2>What it does</h2><p>OpeningFit identifies openings and recurring positions, compares results and available behavioural signals, and creates practical repertoire and training guidance. It is not a chess engine, a coaching qualification, or a universal judgement of an opening.</p><p><a href={supportPath("general")}>Contact the builder</a></p></>,
    how: <><h1>How OpeningFit analysis works</h1><p>This page describes the current report method and enforced public limits. It is product documentation, not a claim that every public game can be analysed.</p><ol><li><strong>Fetch.</strong> OpeningFit requests public Chess.com or Lichess profile and game records for the username submitted. It never asks for the platform password.</li><li><strong>Filter.</strong> The selected date window and supported time-control setting determine eligible games. Missing or invalid PGN, unsupported game types, duplicates and games without enough legal opening moves are excluded and reported by category.</li><li><strong>Limit.</strong> At most <strong>{analysisContract.analysisGameLimit} eligible games</strong> enter one import analysis. Free accounts can request up to {analysisContract.freeHistoryMonths} months of history; Plus can request up to {analysisContract.plusHistoryMonths} months. A shorter public history can produce fewer games.</li><li><strong>Classify.</strong> Move sequences and opening metadata identify an opening and the player colour. The report separates openings played by the user from openings faced as White or Black. Unusual move orders and transpositions can remain ambiguous.</li><li><strong>Decide.</strong> Repeated, sufficiently supported samples can become an established strength or primary problem. One-game samples remain insufficient data. The report selects at most one established strength, one primary problem and exactly one next training action.</li></ol><details open><summary>Scores, results and confidence</summary><p>An opening score rate is wins plus half of draws, divided by games in that opening sample. It is not the same as win rate. The OpeningFit Score runs from 0 to 100 and combines repertoire stability (22%), White results (20%), Black results (20%), evidence coverage (18%), weakness control (12%) and a current sample-consistency proxy (8%). It is not a chess rating or an engine evaluation. Current formula version: <code>openingfit_score_v1</code>.</p><p>Fewer than five classified games makes the overall score provisional. Opening-level recommendations also depend on sufficient repeated evidence, ownership context and the available game sample. Rankings choose among supported candidates; they do not prove that an opening is objectively best.</p></details><details><summary>What OpeningFit does not do</summary><p>OpeningFit does not provide full-game engine analysis, verify a player’s identity, inspect private games, guarantee improvement, or judge an opening’s universal theoretical soundness. Results can change when the date window, time controls, available public games, classification, formula version or comparison baseline changes.</p></details><p><a href="/report/sample">Inspect the labelled sample report</a> or <a href={supportPath("general")}>ask a methodology question</a>.</p></>,
    privacy: <><h1>Data and privacy</h1><h2>Public chess data</h2><p>OpeningFit fetches public username/profile fields, ratings where available, game records, moves/PGNs, results, dates and time controls from Chess.com or Lichess. It never asks for your chess-platform password.</p><h2>Anonymous use</h2><p>The latest report, repertoire choices, training progress, active session and preferences may be stored in your browser. The backend also keeps a latest-result/profile cache and short import history keyed by the public platform username, and may retain restrained operational analytics and feedback. Browser data stays on that device unless you clear it.</p><h2>Referral links</h2><p>If you follow or enter a referral code, OpeningFit stores the code, partner name, a random browser identifier and capture/expiry dates in your browser for up to 30 days. It records the code, random identifier, landing path and visit time in Supabase to prevent duplicate visit counts and attribute a later account or purchase. It does not store the browser user agent for referral tracking.</p><h2>Account use</h2><p>Authenticated users can store profile details, reports, analysed game records, repertoire/training state, activity and progress history in Supabase so they can restore it. If a valid referral is attached, OpeningFit also stores the referring partner, referral code, account identifier, purchase status and commission audit amounts. Stripe processes payments and retains payment/accounting records under its own obligations; OpeningFit stores entitlement and limited Stripe reference fields, not card details. Vercel hosts the web application and product analytics may record restrained route/event data.</p><h2>Deletion</h2><p>Account settings provide a confirmed deletion action. Deleting the authenticated account removes the auth user and user-owned application rows, including its referral attribution, through database cascades; it also removes matching cached profiles and clears OpeningFit browser state on that device. Stripe may retain transaction records where legally or operationally required.</p><p>This plain-language page describes current product behaviour but is not a substitute for professional legal review. <a href={supportPath("data")}>Ask a data question</a>.</p></>,
    terms: <><h1>OpeningFit terms and limitations</h1><p>OpeningFit provides training guidance from available public game history. Recommendations do not guarantee results and are not objective assessments of opening soundness. Classification, platform availability and incomplete records can affect results. Users remain responsible for repertoire choices and can override or dismiss recommendations.</p><p>Payments are handled securely by Stripe. For purchase, access or refund questions, use <a href={supportPath("payment")}>payment support</a>.</p></>,
    changelog: <><h1>OpeningFit changelog</h1><p>User-facing improvements, without internal security or infrastructure details.</p>{CHANGELOG.map((item) => <article key={`${item.date}-${item.improvement}`}><time>{item.date}</time><h2>{item.improvement}</h2><p>{item.outcome}</p></article>)}</>,
  };
  return <div className="publicTrustPage">{appTopNav()}<main className="publicTrustContent">{sections[page]}</main><footer><a href="/about">About</a><a href="/how-it-works">How analysis works</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/changelog">Changelog</a><a href={supportPath("general")}>Support</a></footer></div>;
}
