import { useEffect, useMemo, useState } from "react";
import { buildReturningProgress, orderedCompletedReports } from "../lib/progressExperience";
import { REPERTOIRE_STORAGE_KEY } from "../lib/repertoireWorkspace";
import { trackProductEvent } from "../lib/productAnalytics";
import "./RetentionJourneyPage.css";

const readRepertoire = () => { try { return JSON.parse(localStorage.getItem(REPERTOIRE_STORAGE_KEY) || "null"); } catch { return null; } };
const formatDate = (value) => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "Unavailable";

export default function RetentionJourneyPage({ user, data, reportHistory = [], activityHistory = [], onNavigate }) {
  const repertoire = readRepertoire();
  const model = useMemo(() => buildReturningProgress({ user, currentReport: data, reportHistory, activity: activityHistory, repertoire }), [user, data, reportHistory, activityHistory, repertoire]);
  const reports = useMemo(() => orderedCompletedReports(reportHistory), [reportHistory]);
  const [dismissed, setDismissed] = useState([]);
  const comparison = model.comparison;
  useEffect(() => { if (model.newGamesReliable && model.newGames > 0) void trackProductEvent("new_games_detected", { newGames: model.newGames, source: "progress_page" }, { onceKey: String(model.lastDate) }); if (comparison.resolved.length) void trackProductEvent("resolved_issue_viewed", { resultCategory: "resolved", games: comparison.resolved.length, source: "progress_page" }, { onceKey: String(comparison.currentDate) }); }, [comparison.currentDate, comparison.resolved.length, model.lastDate, model.newGames, model.newGamesReliable]);
  const notices = [
    model.newGamesReliable && model.newGames > 0 ? { key: "games", text: `${model.newGames} new eligible game${model.newGames === 1 ? " is" : "s are"} available for reanalysis.` } : null,
    comparison.available ? { key: "comparison", text: "A completed report comparison is ready." } : null,
    model.issue ? { key: "issue", text: `${model.issue.name || model.issue.opening} still needs attention.` } : null,
    !String(model.coverage).startsWith("3 ") ? { key: "coverage", text: "At least one core repertoire category remains unresolved." } : null,
  ].filter(Boolean).filter((notice) => !dismissed.includes(notice.key));

  return <section className="retentionJourneyPage progressExperience" id="journey-page" aria-labelledby="journey-title">
    <header className="journeyHero"><div><p className="eyebrow">Progress</p><h1 id="journey-title">Your opening improvement cycle</h1><p>Analyse, choose a repertoire, train, play new games, then compare another completed report.</p></div><button className="primaryBtn" type="button" onClick={() => onNavigate?.("analyse")}>{model.shouldReanalyse ? "Reanalyse now" : "Check for new games"}</button></header>
    {notices.length ? <section className="journeyCard progressNotices" aria-label="Progress notices">{notices.map((notice) => <article key={notice.key}><p>{notice.text}</p><button type="button" onClick={() => setDismissed((items) => [...items, notice.key])}>Dismiss</button></article>)}</section> : null}
    <section className="journeyCard"><div className="journeySectionHeader"><div><p className="eyebrow">Current state</p><h2>Opening health and repertoire</h2></div><span>Last report {formatDate(model.lastDate)}</span></div><div className="journeyMiniGrid"><article><span>Opening health</span><strong>{model.health ?? "Unavailable"}</strong></article><article><span>Coverage</span><strong>{model.coverage}</strong></article><article><span>Needs attention</span><strong>{model.issue?.name || model.issue?.opening || "No repeated issue identified"}</strong></article><article><span>Next training</span><strong>{model.nextTraining}</strong></article></div>{model.newGamesReliable ? <p>{model.newGames ? `${model.newGames} verified new eligible games can be included.` : "No verified new eligible games are currently reported."}</p> : <p>OpeningFit cannot verify a lightweight new-game count from the current API response. Checking does not start a full analysis automatically.</p>}</section>
    <section className="journeyCard"><div className="journeySectionHeader"><div><p className="eyebrow">Recent report changes</p><h2>{comparison.available ? "Latest completed reports compared" : "A second report unlocks comparison"}</h2></div></div>{comparison.available ? <><div className="journeyMetricRow"><span><strong>{comparison.health.delta === null ? "—" : `${comparison.health.delta > 0 ? "+" : ""}${comparison.health.delta}`}</strong>Opening health</span><span><strong>{comparison.trainingCompleted}</strong>Training completions between reports</span><span><strong>{comparison.newIssues.length}</strong>New weaknesses</span><span><strong>{comparison.resolved.length}</strong>Resolved issues</span></div><p>These changes occurred after the previous report; they do not prove that training caused them.</p>{comparison.changes.length ? <ul>{comparison.changes.map((change) => <li key={change.name}><strong>{change.name}:</strong> Fit {change.fitDelta > 0 ? "+" : ""}{change.fitDelta ?? "unchanged"}; confidence {change.confidenceBefore} → {change.confidenceNow}</li>)}</ul> : <p>No comparable opening-level changes are available.</p>}</> : <p>Only completed, non-duplicate reports are compared.</p>}</section>
    <section className="journeyCard"><div className="journeySectionHeader"><div><p className="eyebrow">Training progress</p><h2>Meaningful practice outcomes</h2></div></div><div className="journeyMiniGrid"><article><span>Lines practised</span><strong>{model.training.length}</strong></article><article><span>Most recent completion</span><strong>{formatDate(model.training[0]?.created_at || model.training[0]?.createdAt)}</strong></article><article><span>Last trained opening</span><strong>{model.training[0]?.payload?.opening || model.training[0]?.opening || "Unavailable"}</strong></article><article><span>Still weak</span><strong>{model.issue?.name || model.issue?.opening || "No repeated issue identified"}</strong></article></div></section>
    <section className="journeyCard"><div className="journeySectionHeader"><div><p className="eyebrow">Recurring and resolved issues</p><h2>Evidence across reports</h2></div></div><div className="journeyChartGrid"><article><strong>Recurring or new</strong>{comparison.newIssues.length ? <ul>{comparison.newIssues.map((issue) => <li key={issue.name}>{issue.name} · {issue.frequency} games · {issue.confidence}</li>)}</ul> : <p>No newly recurring issue is supported by the comparison.</p>}</article><article><strong>Resolved</strong>{comparison.resolved.length ? <ul>{comparison.resolved.map((issue) => <li key={issue.name}>{issue.name}: {issue.frequency} → {issue.recentFrequency} games · {issue.currentConfidence}{issue.supportingGames.length ? ` · ${issue.supportingGames.length} supporting games` : ""}</li>)}</ul> : <p>No issue meets the strict reduction and confidence threshold yet.</p>}</article></div></section>
    <section className="journeyCard"><div className="journeySectionHeader"><div><p className="eyebrow">Report history</p><h2>{reports.length} completed report{reports.length === 1 ? "" : "s"}</h2></div></div>{reports.length ? <ol className="progressReportHistory">{reports.map((row) => <li key={row.id || row.snapshot_key || row.created_at}><time>{formatDate(row.created_at || row.createdAt || row.summary?.reportDate)}</time><strong>{row.summary?.username || row.report?.username || "Opening report"}</strong><span>{row.summary?.games ?? row.report?.gamesImported ?? "—"} games</span></li>)}</ol> : <p>No completed report history is available.</p>}</section>
  </section>;
}
