"""Reproduce the legacy import dependency snapshot from the reviewed release.

Run from the repository root. No network, runtime execution, or credentials.
"""
import ast
import hashlib
import json
from pathlib import Path
import subprocess

BASE = "054626e762c419c6c4b1477c4a7adef5210177bb"
DEST = Path("backend/legacy_reports")


def source(path):
    return subprocess.check_output(["git", "show", f"{BASE}:{path}"]).decode("utf-8")


def main():
    text = source("backend/main.py")
    tree = ast.parse(text)
    functions = {node.name: node for node in tree.body if isinstance(node, ast.FunctionDef)}
    selected, pending = set(), ["run_import_route", "compact_analysis_result", "demo_profile"]
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        selected.add(name)
        pending.extend(node.id for node in ast.walk(functions[name])
                       if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
                       and node.id in functions and node.id not in selected)
    # Frozen calculation imports (including their transitive local imports).
    references = {item.id for name in selected for item in ast.walk(functions[name]) if isinstance(item, ast.Name)}
    imports = [node for node in tree.body if isinstance(node, ast.ImportFrom)
               and any((alias.asname or alias.name) in references for alias in node.names)
               and (node.module.startswith("analysis.") or node.module in {"opening_detection", "intelligence"})]
    modules = {node.module for node in imports}
    records = {}
    while modules:
        module = modules.pop()
        rel = module.replace(".", "/") + ".py"
        if rel in records:
            continue
        original = source("backend/" + rel)
        for node in ast.walk(ast.parse(original)):
            if isinstance(node, ast.ImportFrom) and node.level and node.module:
                modules.add(module.rsplit('.', node.level)[0] + '.' + node.module)
            if isinstance(node, ast.ImportFrom) and node.module and (
                node.module.startswith("analysis.") or node.module in {"opening_detection", "intelligence"}
            ):
                modules.add(node.module)
        records[rel] = hashlib.sha256(original.encode()).hexdigest()
        copied = original.replace("from analysis.", "from legacy_reports.analysis.").replace(
            "from backend.analysis.", "from legacy_reports.analysis.").replace(
            "from opening_detection import", "from legacy_reports.opening_detection import").replace(
            "from backend.opening_detection import", "from legacy_reports.opening_detection import")
        target = DEST / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(copied, encoding="utf-8", newline="\n")
    (DEST / "__init__.py").write_text('"""Frozen release calculations; see manifest.json and adapter.py."""\n')
    (DEST / "analysis/__init__.py").write_text("")
    lines = text.splitlines(keepends=True)
    chunks = ["# Generated by scripts/freeze_legacy_reports.py; do not edit calculations.\n",
              "from __future__ import annotations\n"]
    # Function defaults use constants/types from main; import only the stable default dependencies.
    chunks.append("from typing import *\n")
    for node in imports:
        chunk = "".join(lines[node.lineno - 1:node.end_lineno])
        chunks.append(chunk.replace("from analysis.", "from legacy_reports.analysis.").replace(
            "from opening_detection import", "from legacy_reports.opening_detection import").replace(
            "from intelligence import", "from legacy_reports.intelligence import"))
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in selected:
            if node.decorator_list and node.name != "demo_profile":
                raise ValueError(f"Unexpected route dependency: {node.name}")
            chunks.append("\n\n" + "".join(lines[node.lineno - 1:node.end_lineno]))
    (DEST / "pipeline.py").write_text("\n".join(chunks), encoding="utf-8", newline="\n")
    (DEST / "manifest.json").write_text(json.dumps({"baseline": BASE, "functions": sorted(selected),
        "main_sha256": hashlib.sha256(text.encode()).hexdigest(), "modules": dict(sorted(records.items()))}, indent=2) + "\n")
    print(f"Frozen {len(selected)} pipeline functions and {len(records)} calculation modules from {BASE}")


if __name__ == "__main__":
    main()
