from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional


OpeningCatalogItem = Dict[str, Any]


def rating_band(low: int, high: int) -> List[int]:
    return [low, high]


OPENING_RECOMMENDATION_CATALOG: List[OpeningCatalogItem] = [
    {
        "name": "Vienna Game",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C25-C29",
        "style_tags": ["open", "tactical", "initiative", "fast-development"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "open centre with quick kingside pressure",
        "good_for": [
            "Players who like active piece play without memorising the full Ruy Lopez",
            "Players who want practical attacking chances after 1.e4 e5",
        ],
        "bad_for": [
            "Players who want a completely quiet system",
            "Players who dislike early central tension",
        ],
        "recommended_rating_band": rating_band(900, 1900),
        "fit_weights": {
            "tactical_tendency": 0.22,
            "open_position_preference": 0.22,
            "development_speed": 0.18,
            "early_attack_frequency": 0.10,
            "king_safety_risk": -0.08,
        },
    },
    {
        "name": "Vienna Gambit",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C25-C29",
        "style_tags": ["open", "gambit", "tactical", "forcing"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "medium",
        "typical_position_type": "sharp open centre with early f-pawn pressure",
        "good_for": [
            "Players who enjoy initiative and forcing lines",
            "Players who score well in short tactical games",
        ],
        "bad_for": [
            "Players who dislike sacrificing structure or pawns",
            "Players with high king safety risk who do not castle reliably",
        ],
        "recommended_rating_band": rating_band(1000, 1900),
        "fit_weights": {
            "tactical_tendency": 0.27,
            "gambit_comfort": 0.24,
            "open_position_preference": 0.20,
            "early_attack_frequency": 0.14,
            "king_safety_risk": -0.14,
        },
    },
    {
        "name": "Italian Game",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C50-C59",
        "style_tags": ["open", "classical", "development", "flexible"],
        "difficulty": "easy",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "classical open game with natural development",
        "good_for": [
            "Players who want active chess with simple development rules",
            "Players building a first serious 1.e4 repertoire",
        ],
        "bad_for": [
            "Players who want to avoid all forcing tactics",
            "Players who prefer closed manoeuvring from move one",
        ],
        "recommended_rating_band": rating_band(700, 2000),
        "fit_weights": {
            "development_speed": 0.24,
            "open_position_preference": 0.18,
            "tactical_tendency": 0.16,
            "castling_consistency": 0.12,
            "opening_phase_stability": 0.10,
        },
    },
    {
        "name": "Evans Gambit",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C51-C52",
        "style_tags": ["open", "gambit", "tactical", "initiative"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "medium",
        "typical_position_type": "open Italian structures with sacrificed b-pawn initiative",
        "good_for": [
            "Players who want attacking chances from familiar Italian positions",
            "Players comfortable trading material for tempo",
        ],
        "bad_for": [
            "Players who dislike early calculation",
            "Players who want low-risk equality plans",
        ],
        "recommended_rating_band": rating_band(1000, 1900),
        "fit_weights": {
            "gambit_comfort": 0.26,
            "tactical_tendency": 0.24,
            "open_position_preference": 0.20,
            "development_speed": 0.12,
            "king_safety_risk": -0.12,
        },
    },
    {
        "name": "Scotch Game",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C44-C45",
        "style_tags": ["open", "tactical", "central", "forcing"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "open centre with fast development",
        "good_for": [
            "Players who like open central positions",
            "Players who want active piece play without learning the full Ruy Lopez",
        ],
        "bad_for": [
            "Players who dislike early calculation",
            "Players who want a quiet system setup",
        ],
        "recommended_rating_band": rating_band(900, 1800),
        "fit_weights": {
            "tactical_tendency": 0.25,
            "open_position_preference": 0.25,
            "development_speed": 0.15,
            "gambit_comfort": 0.10,
            "endgame_conversion": 0.05,
            "king_safety_risk": -0.10,
        },
    },
    {
        "name": "Queen's Gambit",
        "colour": "white",
        "against": "1...d5",
        "eco_family": "D06-D69",
        "style_tags": ["central", "positional", "space", "strategic"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "central space advantage with long-term pressure",
        "good_for": [
            "Players who like building central pressure",
            "Players who want a serious mainline repertoire without immediate chaos",
        ],
        "bad_for": [
            "Players who dislike pawn-structure planning",
            "Players who only want forcing tactical play",
        ],
        "recommended_rating_band": rating_band(900, 2200),
        "fit_weights": {
            "positional_tendency": 0.24,
            "central_pawn_break_frequency": 0.16,
            "closed_position_comfort": 0.14,
            "endgame_conversion": 0.12,
            "opening_phase_stability": 0.10,
        },
    },
    {
        "name": "London System",
        "colour": "white",
        "against": "any",
        "eco_family": "D02",
        "style_tags": ["system", "solid", "low-theory", "positional"],
        "difficulty": "easy",
        "theory_load": "low",
        "tactical_risk": "low",
        "strategic_risk": "low",
        "typical_position_type": "stable system setup with repeatable development",
        "good_for": [
            "Players who want a reliable setup against many Black responses",
            "Players who need opening stability and simple plans",
        ],
        "bad_for": [
            "Players who want maximum opening pressure",
            "Players who get bored by repeatable structures",
        ],
        "recommended_rating_band": rating_band(600, 1800),
        "fit_weights": {
            "opening_phase_stability": 0.26,
            "positional_tendency": 0.18,
            "closed_position_comfort": 0.14,
            "king_safety_risk": 0.08,
            "tactical_tendency": -0.08,
        },
    },
    {
        "name": "Jobava London",
        "colour": "white",
        "against": "any",
        "eco_family": "D00-D02",
        "style_tags": ["system", "tactical", "surprise", "initiative"],
        "difficulty": "medium",
        "theory_load": "low",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "London-style setup with Nc3 and kingside attacking chances",
        "good_for": [
            "Players who like system openings but still want attacking chances",
            "Players who want practical surprise value",
        ],
        "bad_for": [
            "Players who dislike unusual early piece placement",
            "Players who want purely classical central play",
        ],
        "recommended_rating_band": rating_band(900, 1900),
        "fit_weights": {
            "tactical_tendency": 0.20,
            "early_attack_frequency": 0.16,
            "opening_phase_stability": 0.16,
            "development_speed": 0.12,
            "king_safety_risk": -0.06,
        },
    },
    {
        "name": "English Opening",
        "colour": "white",
        "against": "any",
        "eco_family": "A10-A39",
        "style_tags": ["flexible", "positional", "transpositional", "strategic"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "low",
        "strategic_risk": "medium",
        "typical_position_type": "flexible flank opening with delayed central commitment",
        "good_for": [
            "Players who like manoeuvring and transpositions",
            "Players who want to avoid heavily forced 1.e4 theory",
        ],
        "bad_for": [
            "Players who need direct early tactics",
            "Players who dislike subtle move-order choices",
        ],
        "recommended_rating_band": rating_band(1100, 2200),
        "fit_weights": {
            "positional_tendency": 0.24,
            "closed_position_comfort": 0.18,
            "endgame_conversion": 0.12,
            "opening_phase_stability": 0.10,
            "tactical_tendency": -0.06,
        },
    },
    {
        "name": "Ruy Lopez",
        "colour": "white",
        "against": "1...e5",
        "eco_family": "C60-C99",
        "style_tags": ["classical", "positional", "pressure", "mainline"],
        "difficulty": "hard",
        "theory_load": "high",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "long-term central and queenside pressure after classical development",
        "good_for": [
            "Players who want a lifetime 1.e4 mainline",
            "Players who like strategic pressure with tactical moments",
        ],
        "bad_for": [
            "Players who want low theory",
            "Players who need immediate forcing play every game",
        ],
        "recommended_rating_band": rating_band(1300, 2400),
        "fit_weights": {
            "positional_tendency": 0.22,
            "development_speed": 0.14,
            "opening_phase_stability": 0.14,
            "endgame_conversion": 0.10,
            "theory_tolerance": 0.10,
        },
    },
    {
        "name": "King's Indian Attack",
        "colour": "white",
        "against": "any",
        "eco_family": "A07-A08",
        "style_tags": ["system", "kingside", "closed", "attacking"],
        "difficulty": "medium",
        "theory_load": "low",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "closed kingside attacking setup with flexible centre",
        "good_for": [
            "Players who like repeatable plans and kingside attacks",
            "Players who are comfortable in slower buildup positions",
        ],
        "bad_for": [
            "Players who need immediate central clarity",
            "Players who dislike closed manoeuvring",
        ],
        "recommended_rating_band": rating_band(900, 1900),
        "fit_weights": {
            "closed_position_comfort": 0.20,
            "early_attack_frequency": 0.14,
            "opening_phase_stability": 0.14,
            "castling_consistency": 0.10,
            "open_position_preference": -0.08,
        },
    },
    {
        "name": "Smith-Morra Gambit",
        "colour": "white",
        "against": "Sicilian Defence",
        "eco_family": "B21",
        "style_tags": ["gambit", "open", "tactical", "initiative"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "medium",
        "typical_position_type": "open Sicilian structure with sacrificed c-pawn initiative",
        "good_for": [
            "Players who dislike slow anti-Sicilian manoeuvring",
            "Players who score well from rapid development and initiative",
        ],
        "bad_for": [
            "Players uncomfortable playing a pawn down",
            "Players who prefer quiet anti-Sicilian systems",
        ],
        "recommended_rating_band": rating_band(1000, 1900),
        "fit_weights": {
            "gambit_comfort": 0.28,
            "tactical_tendency": 0.24,
            "development_speed": 0.16,
            "open_position_preference": 0.16,
            "king_safety_risk": -0.12,
        },
    },
    {
        "name": "Caro-Kann Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B10-B19",
        "style_tags": ["solid", "structure", "positional", "low-risk"],
        "difficulty": "easy",
        "theory_load": "medium",
        "tactical_risk": "low",
        "strategic_risk": "low",
        "typical_position_type": "solid pawn structure with reliable development and endgame chances",
        "good_for": [
            "Players who want a dependable answer to 1.e4",
            "Players who score well in simplified or structured positions",
        ],
        "bad_for": [
            "Players who want immediate counterattack every game",
            "Players who dislike slightly cramped positions",
        ],
        "recommended_rating_band": rating_band(700, 2200),
        "fit_weights": {
            "positional_tendency": 0.22,
            "castling_consistency": 0.12,
            "simplified_position_comfort": 0.14,
            "endgame_conversion": 0.12,
            "king_safety_risk": 0.08,
            "early_attack_frequency": -0.06,
        },
    },
    {
        "name": "French Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "C00-C19",
        "style_tags": ["closed", "counterattack", "structure", "strategic"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "locked centre with pawn breaks and queenside counterplay",
        "good_for": [
            "Players comfortable with closed centres and pawn breaks",
            "Players who like counterattacking after absorbing space",
        ],
        "bad_for": [
            "Players who hate cramped light-square bishops",
            "Players who need open positions immediately",
        ],
        "recommended_rating_band": rating_band(900, 2200),
        "fit_weights": {
            "closed_position_comfort": 0.24,
            "central_pawn_break_frequency": 0.18,
            "positional_tendency": 0.16,
            "king_safety_risk": 0.06,
            "open_position_preference": -0.10,
        },
    },
    {
        "name": "Sicilian Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B20-B99",
        "style_tags": ["asymmetric", "tactical", "counterattack", "open"],
        "difficulty": "hard",
        "theory_load": "high",
        "tactical_risk": "high",
        "strategic_risk": "medium",
        "typical_position_type": "asymmetric open or semi-open centre with counterplay",
        "good_for": [
            "Players who like imbalance and playing for a win with Black",
            "Players who handle tactics and open files well",
        ],
        "bad_for": [
            "Players who want low theory",
            "Players who struggle with king safety under pressure",
        ],
        "recommended_rating_band": rating_band(1200, 2400),
        "fit_weights": {
            "tactical_tendency": 0.24,
            "open_position_preference": 0.18,
            "central_pawn_break_frequency": 0.14,
            "early_attack_frequency": 0.10,
            "king_safety_risk": -0.12,
        },
    },
    {
        "name": "Scandinavian Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B01",
        "style_tags": ["direct", "simple", "open", "practical"],
        "difficulty": "easy",
        "theory_load": "low",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "early central clarification with simple development",
        "good_for": [
            "Players who want a direct low-theory answer to 1.e4",
            "Players who like early central contact",
        ],
        "bad_for": [
            "Players who dislike moving the queen early",
            "Players seeking rich mainline strategic battles",
        ],
        "recommended_rating_band": rating_band(700, 1800),
        "fit_weights": {
            "open_position_preference": 0.18,
            "development_speed": 0.16,
            "opening_phase_stability": 0.14,
            "tactical_tendency": 0.10,
            "king_safety_risk": -0.06,
        },
    },
    {
        "name": "Scandinavian Portuguese/Icelandic Gambit Ideas",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B01",
        "style_tags": ["gambit", "tactical", "surprise", "initiative"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "high",
        "typical_position_type": "sharp Scandinavian gambit play with rapid piece activity",
        "good_for": [
            "Players who want surprise weapons against 1.e4",
            "Players with high gambit comfort and attacking instincts",
        ],
        "bad_for": [
            "Players who need objectively quiet positions",
            "Players who lose control when down material",
        ],
        "recommended_rating_band": rating_band(1000, 1800),
        "fit_weights": {
            "gambit_comfort": 0.30,
            "tactical_tendency": 0.24,
            "early_attack_frequency": 0.14,
            "development_speed": 0.12,
            "king_safety_risk": -0.14,
        },
    },
    {
        "name": "1...e5 Classical",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "C20-C99",
        "style_tags": ["classical", "open", "development", "fundamental"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "classical open games with natural development and central tension",
        "good_for": [
            "Players who want to learn core opening principles",
            "Players comfortable with open games and early development",
        ],
        "bad_for": [
            "Players who want to avoid White's mainline choices",
            "Players who dislike direct central contact",
        ],
        "recommended_rating_band": rating_band(700, 2200),
        "fit_weights": {
            "development_speed": 0.22,
            "open_position_preference": 0.18,
            "castling_consistency": 0.12,
            "tactical_tendency": 0.10,
            "opening_phase_stability": 0.08,
        },
    },
    {
        "name": "Pirc Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B07-B09",
        "style_tags": ["hypermodern", "counterattack", "flexible", "closed"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "high",
        "typical_position_type": "hypermodern structure inviting White's centre before counterplay",
        "good_for": [
            "Players comfortable with delayed central counterplay",
            "Players who like flexible structures and imbalances",
        ],
        "bad_for": [
            "Players who struggle under early space pressure",
            "Players with poor king safety habits",
        ],
        "recommended_rating_band": rating_band(1100, 2100),
        "fit_weights": {
            "closed_position_comfort": 0.18,
            "central_pawn_break_frequency": 0.16,
            "positional_tendency": 0.12,
            "king_safety_risk": -0.14,
            "development_speed": 0.08,
        },
    },
    {
        "name": "Modern Defence",
        "colour": "black",
        "against": "1.e4",
        "eco_family": "B06",
        "style_tags": ["hypermodern", "flexible", "closed", "counterattack"],
        "difficulty": "medium",
        "theory_load": "low",
        "tactical_risk": "medium",
        "strategic_risk": "high",
        "typical_position_type": "flexible kingside fianchetto with delayed central challenge",
        "good_for": [
            "Players who enjoy flexible move orders",
            "Players comfortable letting opponents build a centre",
        ],
        "bad_for": [
            "Players who need immediate equality by force",
            "Players who often get punished for slow development",
        ],
        "recommended_rating_band": rating_band(1000, 2000),
        "fit_weights": {
            "closed_position_comfort": 0.18,
            "positional_tendency": 0.14,
            "opening_phase_stability": 0.10,
            "development_speed": -0.06,
            "king_safety_risk": -0.12,
        },
    },
    {
        "name": "Queen's Gambit Declined",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "D30-D69",
        "style_tags": ["solid", "positional", "classical", "structure"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "low",
        "strategic_risk": "low",
        "typical_position_type": "classical central structure with resilient defence",
        "good_for": [
            "Players who want a sound answer to 1.d4",
            "Players who like solid development and clear pawn breaks",
        ],
        "bad_for": [
            "Players who want immediate tactical chaos",
            "Players who dislike symmetrical structures",
        ],
        "recommended_rating_band": rating_band(800, 2300),
        "fit_weights": {
            "positional_tendency": 0.24,
            "closed_position_comfort": 0.16,
            "castling_consistency": 0.12,
            "endgame_conversion": 0.10,
            "tactical_tendency": -0.04,
        },
    },
    {
        "name": "Slav Defence",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "D10-D19",
        "style_tags": ["solid", "structure", "active", "classical"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "low",
        "typical_position_type": "solid d4 defence with active light-square bishop options",
        "good_for": [
            "Players who want solidity without burying the c8 bishop",
            "Players who like clear queenside structure",
        ],
        "bad_for": [
            "Players who dislike slower d4 structures",
            "Players who want a low-maintenance system against everything",
        ],
        "recommended_rating_band": rating_band(900, 2200),
        "fit_weights": {
            "positional_tendency": 0.20,
            "development_speed": 0.12,
            "closed_position_comfort": 0.12,
            "opening_phase_stability": 0.10,
            "central_pawn_break_frequency": 0.08,
        },
    },
    {
        "name": "King's Indian Defence",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "E60-E99",
        "style_tags": ["closed", "attacking", "counterattack", "imbalance"],
        "difficulty": "hard",
        "theory_load": "high",
        "tactical_risk": "high",
        "strategic_risk": "high",
        "typical_position_type": "closed centre with kingside pawn storm and counterplay",
        "good_for": [
            "Players who like attacking from closed positions",
            "Players comfortable with risk and long-term counterplay",
        ],
        "bad_for": [
            "Players who dislike cramped positions",
            "Players with poor king safety or slow development",
        ],
        "recommended_rating_band": rating_band(1200, 2300),
        "fit_weights": {
            "closed_position_comfort": 0.20,
            "early_attack_frequency": 0.18,
            "tactical_tendency": 0.16,
            "opposite_side_castling_frequency": 0.08,
            "king_safety_risk": -0.14,
        },
    },
    {
        "name": "Nimzo-Indian Defence",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "E20-E59",
        "style_tags": ["positional", "dynamic", "structure", "classical"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "medium",
        "strategic_risk": "medium",
        "typical_position_type": "dynamic central control with structural pressure",
        "good_for": [
            "Players who like strategic imbalance without reckless risk",
            "Players comfortable playing against doubled pawns and dark-square themes",
        ],
        "bad_for": [
            "Players who need one setup against all move orders",
            "Players who dislike transpositions after 3.Nf3",
        ],
        "recommended_rating_band": rating_band(1100, 2300),
        "fit_weights": {
            "positional_tendency": 0.22,
            "closed_position_comfort": 0.12,
            "central_pawn_break_frequency": 0.12,
            "endgame_conversion": 0.08,
            "tactical_tendency": 0.06,
        },
    },
    {
        "name": "Dutch Defence",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "A80-A99",
        "style_tags": ["imbalance", "attacking", "kingside", "risky"],
        "difficulty": "medium",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "high",
        "typical_position_type": "asymmetric kingside attacking structure after ...f5",
        "good_for": [
            "Players who want winning chances and imbalance against 1.d4",
            "Players comfortable with kingside pawn commitments",
        ],
        "bad_for": [
            "Players with high king safety risk",
            "Players who want quiet equalising systems",
        ],
        "recommended_rating_band": rating_band(1000, 2000),
        "fit_weights": {
            "early_attack_frequency": 0.22,
            "tactical_tendency": 0.18,
            "closed_position_comfort": 0.10,
            "king_safety_risk": -0.18,
            "positional_tendency": -0.04,
        },
    },
    {
        "name": "Benoni/Benko-style Options",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "A56-A79",
        "style_tags": ["imbalance", "gambit", "counterattack", "queenside"],
        "difficulty": "hard",
        "theory_load": "medium",
        "tactical_risk": "high",
        "strategic_risk": "high",
        "typical_position_type": "asymmetric pawn structures with queenside pressure and counterplay",
        "good_for": [
            "Players who like long-term compensation and imbalance",
            "Players comfortable giving space or material for active play",
        ],
        "bad_for": [
            "Players who dislike strategic risk",
            "Players who want simple equalising plans",
        ],
        "recommended_rating_band": rating_band(1200, 2200),
        "fit_weights": {
            "gambit_comfort": 0.18,
            "tactical_tendency": 0.16,
            "closed_position_comfort": 0.12,
            "positional_tendency": 0.08,
            "king_safety_risk": -0.12,
        },
    },
    {
        "name": "Grünfeld Defence",
        "colour": "black",
        "against": "1.d4",
        "eco_family": "D70-D99",
        "style_tags": ["dynamic", "central", "theory-heavy", "counterattack"],
        "difficulty": "hard",
        "theory_load": "high",
        "tactical_risk": "high",
        "strategic_risk": "medium",
        "typical_position_type": "dynamic central counterattack against White's broad pawn centre",
        "good_for": [
            "Players who like active piece play against big centres",
            "Players willing to learn high-theory forcing lines",
        ],
        "bad_for": [
            "Players who want low theory",
            "Players who dislike precise tactical defence",
        ],
        "recommended_rating_band": rating_band(1500, 2400),
        "fit_weights": {
            "tactical_tendency": 0.20,
            "central_pawn_break_frequency": 0.18,
            "open_position_preference": 0.12,
            "development_speed": 0.10,
            "king_safety_risk": -0.10,
        },
    },
]


def all_opening_recommendations() -> List[OpeningCatalogItem]:
    return deepcopy(OPENING_RECOMMENDATION_CATALOG)


def opening_catalog_by_name(name: str) -> Optional[OpeningCatalogItem]:
    target = str(name or "").strip().lower()
    for item in OPENING_RECOMMENDATION_CATALOG:
        if item["name"].lower() == target:
            return deepcopy(item)
    return None


def openings_for_slot(colour: Optional[str] = None, against: Optional[str] = None) -> List[OpeningCatalogItem]:
    colour_key = str(colour or "").strip().lower()
    against_key = str(against or "").strip().lower()

    items = OPENING_RECOMMENDATION_CATALOG
    if colour_key:
        items = [item for item in items if item["colour"].lower() == colour_key]
    if against_key:
        items = [item for item in items if item["against"].lower() == against_key]

    return deepcopy(items)
