import { buildApiUrl } from "./apiBase.js";

export const PRODUCT_EVENTS = ["onboarding_started", "onboarding_completed", "onboarding_skipped", "training_preference_updated", "homepage_viewed", "platform_selected", "username_started", "username_submitted", "account_lookup_succeeded", "account_lookup_failed", "analysis_started", "analysis_failed", "analysis_completed", "report_viewed", "coach_verdict_viewed", "recommendation_expanded", "evidence_viewed", "supporting_game_opened", "fit_explanation_opened", "repertoire_viewed", "opening_added", "opening_replaced", "opening_locked", "recommendation_dismissed", "repertoire_created", "repertoire_change_accepted", "repertoire_change_rejected", "repertoire_training_opened", "training_started", "weekly_plan_started", "training_task_started", "training_task_completed", "weekly_plan_completed", "training_task_failed", "training_answer_revealed", "training_session_completed", "training_impact_viewed", "training_history_opened", "returning_dashboard_viewed", "new_games_detected", "reanalysis_started", "report_comparison_viewed", "report_history_opened", "resolved_issue_viewed", "account_created", "sign_in_completed", "premium_page_viewed", "pricing_viewed", "billing_interval_changed", "checkout_started", "checkout_failed", "checkout_cancelled", "checkout_completed", "entitlement_confirmed", "entitlement_delayed", "subscription_manage_clicked", "upgrade_clicked", "portal_open_failed", "recommendation_feedback_submitted", "general_feedback_submitted", "import_problem_reported"];
PRODUCT_EVENTS.push("weekly_recap_shown", "weekly_recap_opened", "weekly_recap_dismissed", "weekly_recap_action_clicked");
const allowed = new Set(PRODUCT_EVENTS);
const LEGACY_EVENT_MAP = { frontend_import_started: "analysis_started", frontend_import_completed: "analysis_completed", frontend_import_no_games: "analysis_failed", coach_practice_started: "training_started", coach_mission_started: "training_started", coach_repertoire_opened: "repertoire_viewed", coach_diagnostic_opened: "evidence_viewed", premium_upgrade_prompt_selected: "premium_page_viewed", premium_entitlement_confirmed: "entitlement_confirmed", premium_entitlement_delayed: "entitlement_delayed", recommendation_feedback: "recommendation_feedback_submitted" };
const SAFE_KEYS = new Set(["platform", "route", "authenticated", "deviceCategory", "resultCategory", "errorCategory", "source", "access", "stage", "attempts", "feedback", "decision", "confidence", "games", "fetchedGames", "dateRangeEligibleGames", "timeControlEligibleGames", "analysisCandidateGames", "analysedGames", "excludedGames", "gamesImported", "gamesEligible", "gamesClassified", "gamesExcluded", "openingCategory", "hasSessionContext", "newGames", "reportCount", "billingInterval", "sample", "reportKind"]);
const sensitive = /token|authorization|password|secret|email|pgn|payment|card|stripe|sessionid|userid|username|reportidentifier/i;
export function normalizeProductEvent(name) { const normalized = LEGACY_EVENT_MAP[name] || name; return allowed.has(normalized) ? normalized : null; }
export function deviceCategory(width = typeof window !== "undefined" ? window.innerWidth : 1024) { return width < 640 ? "mobile" : width < 1024 ? "tablet" : "desktop"; }
export function safeAnalyticsProperties(properties = {}) { const output = {}; for (const [key, value] of Object.entries(properties || {})) { if (!SAFE_KEYS.has(key) || sensitive.test(key) || value === undefined || value === null) continue; if (["string", "number", "boolean"].includes(typeof value)) output[key] = typeof value === "string" ? value.slice(0, 100) : value; } return output; }
const sentOnce = new Set();
export async function trackProductEvent(name, properties = {}, options = {}) { const event = normalizeProductEvent(name); if (!event) { if (import.meta.env?.DEV) console.warn("OpeningFit analytics rejected unknown event", name); return false; } const data = safeAnalyticsProperties({ route: typeof window !== "undefined" ? window.location.pathname : "/", deviceCategory: deviceCategory(), ...properties }); const dedupeKey = options.onceKey ? `${event}:${options.onceKey}` : ""; if (dedupeKey && sentOnce.has(dedupeKey)) return true; if (dedupeKey) sentOnce.add(dedupeKey); if (import.meta.env?.DEV) console.info("OpeningFit analytics", event, data); try { const response = await fetch(buildApiUrl("/api/analytics/event"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event, data }) }); return response.ok; } catch { return false; } }
export function resetAnalyticsDedupeForTests() { sentOnce.clear(); }
