import test from "node:test";
import assert from "node:assert/strict";
import { Chess } from "chess.js";
import { buildFiniteSession, buildTrainingQueue, evaluateTrainingMove, trainingOutcome } from "./trainingQueue.js";

test("finite queue uses the canonical repeated repair target", () => {
  const repair = { recommendationId: "italian:white", opening: "Italian", openingName: "Italian", role: "played_as_white", repertoireRole: "white", repertoireOwned: true, verdict: "repair", findingType: "opening_weakness", sampleSize: 5, sampleThreshold: 5, evidenceStatus: "sufficient", confidenceLevel: "low", sample: { games: 5, wins: 1, draws: 1, losses: 3, gameIds: ["i1", "i2", "i3", "i4", "i5"] }, trainingAction: { title: "Repair Italian", explanation: "Five games support this repair." } };
  const action = { decisionId: "decision:italian", actionId: "decision:italian", type: "repair_repertoire", verdict: "repair", recommendationId: repair.recommendationId, opening: "Italian", role: "played_as_white", repertoireRole: "white", sample: repair.sample, label: "Repair Italian", reason: "Five games support this repair.", nextAction: "Review the first repeated decision.", trainingDuration: { minutes: 10 }, successCheck: "Finish one review.", confidenceLevel: "low" };
  const queue = buildTrainingQueue({ reportDecision: { schemaVersion: 5, decisionId: action.decisionId, recommendations: [repair], primaryProblem: repair, primaryAction: action, nextTrainingAction: action } });
  assert.equal(queue[0].title, "Italian");
  assert.ok(buildFiniteSession(queue).tasks.length <= 3);
});
test("recurring opening opportunities enter the existing queue first", () => { const target = { opportunityId: "opp-1", openingId: "italian-game", recurrenceCount: 3, explanation: "Repeated repertoire deviation." }; const queue = buildTrainingQueue({ openingTrainingOpportunities: [target], weak_lines: [{ opening: "French", games: 5, losses: 3 }] }); assert.equal(queue[0].target, target); assert.match(queue[0].type, /Opening/); });
test("trustworthy recurring mistakes become canonical position training subjects", () => { const habit = { habitId: "habit-1", habitType: "RECURRING_MISTAKE", canonicalOpeningId: "owens-defense", opening: "Owen's Defence", playedMove: "Nc6", recommendedMove: "c5", occurrenceCount: 6, gameReferences: ["g1"], trainingSubjectId: "opening-position:black_vs_e4:abc" }; const queue = buildTrainingQueue({ recurringOpeningHabits: [habit] }); assert.equal(queue[0].id, "habit:habit-1"); assert.equal(queue[0].target.trainingSubjectId, habit.trainingSubjectId); assert.equal(queue[0].target.recommendedMove, "c5"); });
test("white and black moves are evaluated from the supplied position", () => { assert.equal(evaluateTrainingMove({ attempted: "e4", expected: "e4" }).accepted, true); const game = new Chess(); game.move("e4"); assert.equal(evaluateTrainingMove({ fen: game.fen(), attempted: "c5", expected: "c5" }).accepted, true); });
test("wrong, valid alternative, and invalid line data are safe", () => { assert.equal(evaluateTrainingMove({ attempted: "d4", expected: "e4" }).reason, "wrong"); assert.equal(evaluateTrainingMove({ attempted: "d4", expected: "e4", alternatives: ["d4"] }).alternative, true); assert.equal(evaluateTrainingMove({ attempted: "bad", expected: "e4" }).reason, "illegal"); });
test("training outcomes distinguish retry, reveal, and failure", () => { assert.equal(trainingOutcome({ attempts: 1 }), "correct_first_attempt"); assert.equal(trainingOutcome({ attempts: 2 }), "correct_after_retry"); assert.equal(trainingOutcome({ attempts: 5 }), "repeated_failure"); assert.equal(trainingOutcome({ attempts: 1, revealed: true }), "revealed"); });
test("missing report data produces an empty personalised queue", () => assert.deepEqual(buildTrainingQueue({}), []));
